server:
  port: 8011
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-app?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  main:
    allow-circular-references: true  #??Security

mybatis:
  configuration-properties:
    helperDialect: mysql
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true
  mapper-locations: classpath:mapper/*.xml
redis:
  host: localhost
  port: 6379
  database: 0
  timeout: 1800000
  password:
  lettuce:
    pool:
      max-active: 20 #最大连接数
      max-wait: -1    #最大阻塞等待时间(负数表示没限制)
      max-idle: 5    #最大空闲
      min-idle: 0     #最小空闲
aliyun:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  keyid: LTAI5tBLMSxa4AuECjPmG3hz
  keysecret: deqaCnxpaXuMa2ujxFpD9azaxkzUEl
  bucketname: gulimall-lay